### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by masaedw** [masaedw/cbook#1]
- [x] scope of local variables
- [x] break/continue
- [x] typedef
- [ ] enum
- [ ] struct
- [ ] variadic function
- [ ] goto/label
- [ ] switch-case
- [ ] void
- [ ] _Bool
- [ ] signed/unsigned
- [ ] sizeof typename
- [ ] `?:`
- [ ] logical operators
- [ ] bit operators
- [ ] initializer
- [ ] increment/decrement
- [ ] `*=` `+=` ...
- [ ] backslash in string literals
- [ ] static top-level
- [ ] static in function
- [ ] cast of pointers
- [ ] cast of numeric
- [ ] local typedef
- [ ] local enum
- [ ] local struct
